### PR TITLE
Fix default op-naming, tf.zeros, and compliant tf.constant

### PR DESCRIPTION
**Pull request by chrhansen**
I began implementing [`tf.zeros`](https://www.tensorflow.org/versions/r0.10/api_docs/python/constant_op.html#zeros) (a special kind of constant-op  with all 0s – taking only shape as required argument) and found that our `constant()`-method doesn't work with scalars _and_ doesn't take `shape` as an argument. Writing specs for that, I _then_ discovered that our `default_names`- method uses a character, `:`, that makes it unretrievable from the TensorFlow graph. 

- `:` is not allowed in names on the actual (not the wrapper) TensorFlow graph
- make `constant()` compliant (https://www.tensorflow.org/versions/r0.10/api_docs/python/constant_op.html#constant), e.g. work on scalars and take `shape` as argument
- ... then build `zeros()`

### CODE REVIEW

**Comment by chrhansen** [comment]
At this point this PR only fixes the op-naming issues and adds a few extra specs, but `tf.zeros` is not yet implemented and `tf.constant` is not yet fixed. Merging wont do harm, though.

**Comment by Arafatk** [comment]
@chrhansen I will make the constant work with the specifications soon.
Thanks a lot for this.

**Comment by chrhansen** [comment]
@Arafatk well, wait off with that – as I wrote above I'm already working on that.

**Comment by Arafatk** [comment]
@chrhansen Just one thing, I have done something similar in image branch for this. 
Thanks

**Comment by chrhansen** [comment]
@Arafatk ?

**Comment by Arafatk** [comment]
@chrhansen  In image recognition tutorial, I had made a few changes so that I could read scalars but it was not the best way to do it.

**Pull request merged**
