### PR TITLE
Add shape method to Array, Numeric, and String as cleanup

### PR DESCRIPTION
**Pull request by chrhansen**
As a prep to compliant constant method this PR cleans up `Tensorflow::Tensor` a bit.

### CODE REVIEW

**Comment by chrhansen** [comment]
@Arafatk could you review this PR and merge if it looks good. Two things happened:

1. Renamed `dimension_finder` to `shape` moved it to an extension to `Array`, `Numeric` (integer, float, complex), and `String`. Ideally we should use https://github.com/SciRuby/nmatrix (that has methods like `shape` built in), but the build script is still broken. https://github.com/SciRuby/nmatrix/issues/505 was reported fixed, but when I tried `gem install nmatrix` again this weekend it still doesn't pick the right compiler on Mac, so we can't use `Nmatrix` yet unfortunately
2. Cleanup in `Tensorflow::Tensor`. I think there's still a lot that can be done, but this is a first step.

**Comment by Arafatk** [comment]
@chrhansen  I have used nmatrix before and its really great and I thought about using it myself but did not do it because.
1. It won't support string. 
2. To use the shape method we have to first make a matrix and then find the shape. Also the shape method ignores errors which are very necessary in our case. Like this examples below (take a look at `[7, 8, 9,4] `)
```
2.2.1 :013 > a = N[ [2, 3, 4], [7, 8, 9,4] ]
 => #<NMatrix:0x0000000132c778 shape:[2,3] dtype:int32 stype:dense> 
2.2.1 :014 > a.shape
 => [2, 3] 
```
But still the gem has its own merits. 

Thanks for the pr and tests. It is much better than before.

**Comment by zverok** [comment]
Sorry for being late for the party, but as far as I am concerned, this kind of things (extending core classes with custom methods with "common" names, just to make your library code shorter) is considered really inappropriate approach. 

You did it just to simplify one line of `tensorflow.rb` code, yet you treated the very core classes as "your own".

To be honest, _any_ core class extension in _gems_ should be considered with a great care, and the only (and even that is questionable) appropriate thing is when you provide some new and useful methods for gem user, not just simplify gems internals.

**Comment by chrhansen** [comment]
@zverok I was also on the fence for this, and followed the approach outlined here http://www.justinweiss.com/articles/3-ways-to-monkey-patch-without-making-a-mess/, i.e. putting the extension in namespaced modules, so it should be more obvious down the road, if an error happens in the `shape`-method, where it came from. 

As you can see from my comment above, we unfortunately do not have the luxury of [Numpy's array](http://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html) in Ruby, and the shape is an [integral part of Tensorflow](https://www.tensorflow.org/versions/r0.10/resources/faq.html#tensor-shapes). But perhaps it's better to have `shape` as an instance method inside `Tensorflow::Tensor` (I could also see this as a good option), alternatively make our own `TFArray`-subclass. @Arafatk what do you think? And which class does `Tensorflow::Tensor` compare to in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python?

**Comment by Arafatk** [comment]
@zverok @chrhansen Thanks for the discussion. I think the changes are good but if there is a possibility of having issues in future due to monkey patching then maybe we can have shape as an instance method inside `Tensorflow::Tensor` so that further work could be carried out easily.
@chrhansen For your question, I have taken a ideas from [tensor_util.py](https://github.com/tensorflow/tensorflow/blob/8de7608075c6dd6fcaf8f5c3d921f3611f8e7611/tensorflow/python/framework/tensor_util.py) and [tensorshape.py](https://github.com/tensorflow/tensorflow/blob/8de7608075c6dd6fcaf8f5c3d921f3611f8e7611/tensorflow/python/framework/tensor_shape.py).

**Comment by chrhansen** [comment]
@Arafatk Ok, I'll move `#shape` to `Tensorflow::Tensor`, I agree that's better. It's defined in [ops.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L334) within the `Tensor` class. This file is also where `Graph`-class is defined.

Do you mind if I rename `dimensions` to `shape` to use same terminology as the Python API and documentation?

**Comment by Arafatk** [comment]
@chrhansen That's fine. Thanks.

**Pull request merged**
